#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void ButtonModifyUser( wxCommandEvent& event );
		void ButtonDeleteUser( wxCommandEvent& event );
		void OnAlarmToggleButton( wxCommandEvent& event );
		void OnButtonFinClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members






};

#endif // __EvtFramePrincipal__
